#!/bin/bash

usage () {
    printf "%s" "\
USAGE: 
    install [OPTIONS] [ARGS]

ARGS:
    <WM>
        Window managers, for which you want to install files.

OPTIONS:
    -h, --help
        Show this message.
    --clean
        Clean destinational files from previous installation.
"

exit 1
}

trim () {
    # Use `xargs` for trimming trailing or leading spaces
    echo "$1" | xargs
}


# parse_toml takes path to config and then the name of the variable in the
# config and returns the value of that variable
parse_toml () {
    local file="$1"
    local var_name="$2"
    
    while read -r line 
    do
        local var="$(trim "$(echo "$line" | awk -F "=" '{print $1}')")"

        if [ "$var" == "$var_name" ]; then
            local res="$(trim "$(echo "$line" | awk -F "=" '{print $2}' | tr -d '"')")"
            eval "echo \"$res\""
        fi
        
    done < "$file"
}

install_wm () {
    local wm="$1"
    local profile="profiles/$wm.toml"
    local cache="$(parse_toml "$profile" "cache")"
    local prefix="$(parse_toml "$profile" "prefix")"
    local config_dir="$(parse_toml "$profile" "config_dir")"
    local config_file="$(parse_toml "$profile" "config_file")"
   
    if [ "$CLEAN" -eq 1 ]; then
        rm -r "$prefix"
    fi

    mkdir -p "$cache"
    mkdir -p "$prefix"
    mkdir -p "$config_dir"


    case "$wm" in 
        "bspwm")
            local config="$(echo "$config_dir/$config_file" | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')" 
            sed -i "s/\$\$CONFIG/\"$config\"/g" ixwindow_compiled/bspwm/ixwindow
            ;;

        "i3")
            ;;
    esac
    
    cp "$profile" "$config_dir/$config_file"
    cp -r ixwindow_compiled/* "$prefix"
}

WINDOW_MANAGES=()

if [ $# -eq 0 ]; then
    usage
fi

CLEAN=0

while [ $# -gt 0 ];
do
    case "$1" in 
        "--help" | "-h")
            usage 
            ;;
        "--clean")
            CLEAN=1
            shift
            ;;
        *)
            while [ $# -gt 0 ]; 
            do
                WINDOW_MANAGES+=("$1")
                shift
            done

            ;;
    esac
done

cp -r ixwindow ixwindow_compiled
rm -r ixwindow_compiled/wms

g++ ixwindow_compiled/polybar-xwindow-icon.cpp -o ixwindow_compiled/polybar-xwindow-icon -I/usr/include/opencv4/ -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lX11

for wm in "${WINDOW_MANAGES[@]}"
do
    case "$wm" in
        "bspwm")
            cp -r "ixwindow/wms/bspwm" "ixwindow_compiled/bspwm"
            install_wm "bspwm"
            ;;

        "i3")
            cp -r "ixwindow/wms/i3" "ixwindow_compiled/i3"
            install_wm "i3"
            ;;
    esac
done




rm -r ixwindow_compiled
