#!/bin/bash

trim () {
    # Use `xargs` for trimming trailing or leading spaces
    echo "$1" | xargs
}


# parse_toml takes path to config and then the name of the variable in the
# config and returns the value of that variable
parse_toml () {
    local config="$1"
    local var_name="$2"
    
    while read -r line 
    do
        local var="$(trim "$(echo "$line" | awk -F "=" '{print $1}')")"

        if [ "$var" == "$var_name" ]; then
            trim "$(echo "$line" | awk -F "=" '{print $2}' | tr -d '"')"
        fi
        
    done < "$config"
}
