#!/bin/bash

usage () {
    printf "%s" "\
USAGE: 
    uninstall [OPTIONS] [ARGS]

ARGS:
    <WM>
        Window manager, for which you want to uninstall files.

OPTIONS:
    -h, --help
        Show this message.
    --cache
        Remove cached icons.
    --all
        Remove all ixwindow files, not only for specific wm.
"

exit 1
}

trim () {
    # Use `xargs` for trimming trailing or leading spaces
    echo "$1" | xargs
}


# parse_toml takes path to config and then the name of the variable in the
# config and returns the value of that variable
parse_toml () {
    local file="$1"
    local var_name="$2"
    
    while read -r line 
    do
        local var="$(trim "$(echo "$line" | awk -F "=" '{print $1}')")"

        if [ "$var" == "$var_name" ]; then
            local res="$(trim "$(echo "$line" | awk -F "=" '{print $2}' | tr -d '"')")"
            eval "echo \"$res\""
        fi
        
    done < "$file"
}

remove () {
    local wm="$1"
    
    local profile="profiles/$wm.toml"
    local cache_dir="$(parse_toml "$profile" "cache")"
    local install_dir="$(parse_toml "$profile" "prefix")"
    local config_dir="$(parse_toml "$profile" "config_dir")"


    rm -r "$config_dir"
    rm -r "$install_dir/$wm"

    if [ "$REMOVE_CACHE" -eq 1 ]; then
        rm -r "$cache_dir"
    fi

}


if [ $# -eq 0 ]; then
    usage
fi

REMOVE_CACHE=0
REMOVE_ALL=0

while [ $# -gt 0 ]; 
do
    case "$1" in 
        "--help" | "-h")
            usage 
            ;;
        "--cache")
            REMOVE_CACHE=1
            shift 
            ;;
        "--all")
            REMOVE_ALL=1
            shift
            ;;
        *)
            WM="$1"
            ;;
    esac
done

if [ "$REMOVE_ALL" -eq 1 ]; then
    prefix=""

    for file in profiles/*
    do
        prefix=""
        file="$(basename -- "$file")"
        wm="${file%.*}"
    
        profile="profiles/$wm.toml"
        prefix="$(parse_toml "$profile" "prefix")"

        remove "$wm"
    done

    rm -r "$prefix"
fi

