#!/bin/bash

# Most of the code taken from 
# https://unix.stackexchange.com/questions/48860/how-to-dump-the-icon-of-a-running-x-program

CACHE_DIR="$1"
SIZE="$2"
COLOR="$3"
wid="$4"


get_wm_class() {
    echo "$(xprop -id "$1" WM_CLASS | awk -F '=' '{print $2}' | \
    awk -F ',' '{print $2}' |  tr -d '"' | \
    sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}


mkdir -p "$CACHE_DIR"

WM_CLASS="$(get_wm_class "$wid")"
NAME="$WM_CLASS"
CACHE_FILE="$CACHE_DIR/$NAME"

if [ -f "$CACHE_FILE.jpg" ]; then
    exit 0
fi

# Check if there is an icon for us in xprop, 
# so it won't break the behavior of the script 
if [ -z "$(xprop -id "$wid" | grep "Icon")" ]; then
    exit 0
fi

cmd=(convert -set 'fileNAME:w' '%w' - "${NAME}.png")

split_icons() {
    xprop -id "$wid" -notype 32c _NET_WM_ICON |
    awk -v RS=', | = ' '
        NR == 1         { h  = $1; i++; next }
        NR == i + 1     { x  = $1;        printf "%s = %s", h, x; next }
        NR == i + 2     { s  = x * $1 } { printf ", %s", $1 }
        NR == i + 2 + s { i += s + 2;     printf "\n" }
    '
}

to_pam() {
    perl -0777 -pe '@_=/\d+/g;
    printf "P7\nWIDTH %d\nHEIGHT %d\n", splice@_,0,2;
    printf "DEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n";
    $_=pack "N*", @_;
    s/(.)(...)/$2$1/gs'
}



while read -r data; do to_pam <<< "$data" | "${cmd[@]}"; done < <(split_icons)


convert "$NAME.png" -background $COLOR -flatten -alpha off "$NAME.jpg"
mv "$NAME.jpg" "$CACHE_FILE.jpg" && rm "$NAME.png"

