#!/bin/bash

usage () {
    printf "%s" "\
USAGE: 
    ixwindow-convert [OPTIONS] [FILES]

ARGS:
    <FILES>
        The PNG files (with transparent background) to convert 
        to JPG files format with appropriate size and background color.


OPTIONS:
    -h, --help
        Show this message.

    --size
        Specify size directly. Overwrites config size if both specified.

    --color
        Specify background color directly. Overwrites config size if both specified.

    --cache
        Specify cache folder directly. Overwrites config size if both specified.
"

exit 1
}

while [ $# -gt 0 ];
do
    case "$1" in
        "--help" | "-h")
            usage
            exit 0
            ;;
        "--size")
            size="$2"
            shift 2
            ;;

        "--color")
            color="$2"
            shift 2
            ;;
        "--cache")
            cache_dir="$2"
            shift 2
            ;;
        *)
            while [ $# -gt 0 ]; 
            do
                name="${1%.*}"
                ext="${1##*.}"

                if [ "$ext" = "svg" ]; then
                    inkscape -w 1024 -h 1024 "$name.svg" -o "$name.png" &> /dev/null &&
                    convert "$name.png" -background "$color" -flatten -alpha off "$name.jpg"
                    rm "$name.png"
                else
                    convert "$name.png" -background "$color" -flatten -alpha off "$name.jpg"
                fi

                mv "$name.jpg" "$cache_dir"

                shift 
            done
            ;;
    esac
done

