#!/bin/bash

usage () {
    printf "%s" "\
USAGE: 
    ixwindow-convert [OPTIONS] [FILES]

ARGS:
    <FILES>
        The PNG files (with transparent background) to convert 
        to JPG files format with appropriate size and background color.


OPTOINS:
    -c, --config
        Path to the configuration file for ixwindow.

    -h, --help
        Show this help information.

    --size
        Specify size directly. Overwrites config size if both specified.

    --color
        Specify background color directly. Overwrites config size if both specified.
"

exit 1
}

get_wm () {
    wmctrl -m | awk '{if ($1 == "Name:") print $2}'
}

trim () {
    # Use `xargs` for trimming trailing or leading spaces
    echo "$1" | xargs
}

# parse_toml takes path to config and then the name of the variable in the
# config and returns the value of that variable
parse_toml () {
    local config="$1"
    local var_name="$2"
    
    while read -r line 
    do
        local var="$(trim "$(echo "$line" | awk -F "=" '{print $1}')")"

        if [ "$var" == "$var_name" ]; then
            trim "$(echo "$line" | awk -F "=" '{print $2}' | tr -d '"')"
        fi
        
    done < "$config"
}

get_size () {
    parse_toml "$1" "size"
}

get_color () {
    parse_toml "$1" "color"
}

init_config () {
    local config="$1" 

    # Check if variables size and color were set before
    # and if they were set, we should not overwrite them
    if [ -z "${size+x}" ]; then
        size="$(get_size "$config")"
    fi

    if [ -z "${color+x}" ]; then
        color="$(get_color "$config")"
    fi 
}


config_dir=$$CONFIG_DIR
wm="$(get_wm)"
config_file="$config_dir/$wm/config.toml"

while [ $# -gt 0 ];
do
    case "$1" in
        "--help" | "-h")
            usage
            exit 0
            ;;

        "--config" | "-c")
            config="$2"
            shift 2
            ;;

        "--size")
            size="$2"
            shift 2
            ;;

        "--color")
            color="$2"
            shift 2
            ;;

        *)
            init_config "$config"

            while [ $# -gt 0 ]; 
            do
                name="${1%.*}"

                convert "$1" -resize "$size"x"$size" -background "$color" -flatten -alpha off "$name.jpg"
                shift 
            done
            ;;
    esac
done

